// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_W4UvyMddSFHuJcgG6BHn6LySVf5KNVs',
    appId: '1:1092284736352:web:5eae93b84c3978588b7405',
    messagingSenderId: '1092284736352',
    projectId: 'note-lingo-54cc2',
    authDomain: 'note-lingo-54cc2.firebaseapp.com',
    storageBucket: 'note-lingo-54cc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbG09F4cMgH1jE0v2DIhFHvKQKFv4FIs',
    appId: '1:1092284736352:android:1507b0126b741ff68b7405',
    messagingSenderId: '1092284736352',
    projectId: 'note-lingo-54cc2',
    storageBucket: 'note-lingo-54cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4fTZQcU31Cs3Me_zlCNcLnVHFbfyUPU',
    appId: '1:1092284736352:ios:1400a3ff48eedd9a8b7405',
    messagingSenderId: '1092284736352',
    projectId: 'note-lingo-54cc2',
    storageBucket: 'note-lingo-54cc2.firebasestorage.app',
    iosBundleId: 'com.example.noteLingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4fTZQcU31Cs3Me_zlCNcLnVHFbfyUPU',
    appId: '1:1092284736352:ios:1400a3ff48eedd9a8b7405',
    messagingSenderId: '1092284736352',
    projectId: 'note-lingo-54cc2',
    storageBucket: 'note-lingo-54cc2.firebasestorage.app',
    iosBundleId: 'com.example.noteLingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_W4UvyMddSFHuJcgG6BHn6LySVf5KNVs',
    appId: '1:1092284736352:web:4ce107dfebe0b5428b7405',
    messagingSenderId: '1092284736352',
    projectId: 'note-lingo-54cc2',
    authDomain: 'note-lingo-54cc2.firebaseapp.com',
    storageBucket: 'note-lingo-54cc2.firebasestorage.app',
  );
}
