import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'app_title': 'Note Lingo',
      'welcome': 'Welcome to Note Lingo',
      'record': 'Record',
      'stop': 'Stop',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'transcription': 'Transcription',
      'summary': 'Summary',
      'category': 'Category',
      'language': 'Language',
      'favorite': 'Favorite',
      'unfavorite': 'Unfavorite',
      'share': 'Share',
      'comments': 'Comments',
      'analytics': 'Analytics',
      'settings': 'Settings',
      'logout': 'Logout',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'lecture': 'Lecture',
      'meeting': 'Meeting',
      'interview': 'Interview',
      'personal': 'Personal',
      'other': 'Other',
      'home': 'Home',
      'notes': 'Notes',
      'profile': 'Profile',
      'export': 'Export',
      'recent_notes': 'Recent Notes',
      'no_notes': 'No notes yet',
      'create_first_note': 'Create your first note',
      'tap_record': 'Tap the record button to start',
      'recording': 'Recording...',
      'processing': 'Processing...',
      'transcribing': 'Transcribing...',
      'summarizing': 'Summarizing...',
      'connecting_ai': 'Connecting to AI server...',
      'ai_enhancements': 'AI Enhancements',
      'sentiment': 'Sentiment',
      'speakers': 'Speakers',
      'keywords': 'Keywords',
      'entities': 'Entities',
      'smart_folders': 'Smart Folders',
      'add_comment': 'Add a comment...',
      'no_comments': 'No comments yet',
      'shared_with': 'Shared With',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'created': 'Created',
      'modified': 'Modified',
      'duration': 'Duration',
      'word_count': 'Word Count',
      'transcription_accuracy': 'Transcription Accuracy',
      'progress_stats': 'Progress Stats',
      'total_notes': 'Total Notes',
      'total_minutes': 'Total Minutes',
      'total_words': 'Total Words',
      'current_streak': 'Current Streak',
      'by_category': 'By Category',
      'top_words': 'Top Words',
      'favorites': 'Favorites',
      'offline_mode': 'Offline Mode',
      'retry': 'Retry',
      'failed_to_save': 'Failed to save note',
      'please_try_again': 'Please try again',
      'copied': 'Copied!',
      'confirm_delete': 'Are you sure you want to delete this note?',
      'confirm_logout': 'Are you sure you want to logout?',
      'ai_analyzing': 'AI is analyzing your note...',
      'sentiment_positive': 'Positive',
      'sentiment_negative': 'Negative',
      'sentiment_neutral': 'Neutral',
      'export_pdf': 'Export as PDF',
      'export_docx': 'Export as DOCX',
      'export_txt': 'Export as TXT',
      'archive': 'Archive',
      'unarchive': 'Unarchive',
      'pin': 'Pin',
      'unpin': 'Unpin',
    },
    'si': {
      'app_title': 'Note Lingo',
      'welcome': 'Note Lingo වෙත සාදරයෙන් පිළිගනිමු',
      'record': '녹음',
      'stop': 'නවත්වන්න',
      'save': 'සිටුවන්න',
      'cancel': 'අවලංගු කරන්න',
      'delete': 'මකන්න',
      'edit': 'සංස්කරණය',
      'transcription': 'පිටපතිකරණය',
      'summary': 'සාරාංශ',
      'category': 'කාණ්ඩය',
      'language': 'ඉංග්‍රීසි',
      'favorite': 'ප්‍රිය',
      'unfavorite': 'ප්‍රිය නොවේ',
      'share': 'බෙදා ගන්න',
      'comments': 'අදහස්',
      'analytics': 'විශ්ලේෂණ',
      'settings': 'සිටුවම්',
      'logout': 'ඉවත් වන්න',
      'loading': 'පූරණය වෙමින් පවතී...',
      'error': 'දෝෂය',
      'success': 'සාර්ථකතා',
      'lecture': 'විශ්ව විද්‍යාල',
      'meeting': 'සාමාජිකයින්',
      'interview': 'සම්මුඛ පරීක්ෂණ',
      'personal': 'පෞද්ගලික',
      'other': 'වෙනත්',
      'home': 'ගෙර',
      'notes': 'සටහන්',
      'profile': 'පෙර',
      'export': 'අපනයන',
      'recent_notes': 'මෑතකාලීන සටහන්',
      'no_notes': 'තවමත් සටහන් නොමැත',
      'create_first_note': 'ඔබේ පළමු සටහන සාදන්න',
      'tap_record': 'ඉතිරි කිරීම සඳහා ඇති කිරීම බටන ස්පර්ශ කරන්න',
      'recording': '녹음 වෙමින් පවතී...',
      'processing': 'සකස්කරමින් පවතී...',
      'transcribing': 'පිටපතිකරමින් පවතී...',
      'summarizing': 'සාරාංශ කරමින් පවතී...',
      'connecting_ai': 'AI සර්වරයට සংযුක්ත වෙමින් පවතී...',
      'ai_enhancements': 'AI වර්ධන',
      'sentiment': 'හැඟීම',
      'speakers': 'කතිකයින්',
      'keywords': 'ඇතුළු ඉඩ',
      'entities': 'ඒකක',
      'smart_folders': 'බුද්ධිමත් ෆෝල්ඩර්',
      'add_comment': 'අදහස එක් කරන්න...',
      'no_comments': 'තවමත් අදහස් නොමැත',
      'shared_with': 'සමඟ බෙදා ගනු ලැබ ඇත',
      'search': 'සෙවුම',
      'filter': 'පෙරනය',
      'sort': 'වර්ගීකරණය',
      'created': 'සාදන ලද',
      'modified': 'සංස්කරණය කරන ලද',
      'duration': 'කාලසීමාව',
      'word_count': 'වචන ගණන',
      'transcription_accuracy': 'පිටපතිකරණ නිරවද්‍යතාවය',
      'progress_stats': 'ප්‍රගතිමත් සංඛ්‍යා',
      'total_notes': 'මුළු සටහන්',
      'total_minutes': 'මුළු මිනිත්තු',
      'total_words': 'මුළු වචන',
      'current_streak': 'වර්තමාන පටිපාඩු',
      'by_category': 'කාණ්ඩ අනුව',
      'top_words': 'ඉහළ වචන',
      'favorites': 'ප්‍රිය',
      'offline_mode': 'අබිබැඩ ප්‍රකාරය',
      'retry': 'නැවත උත්සාහ කරන්න',
      'failed_to_save': 'සටහන සිටුවීමට අසමත්',
      'please_try_again': 'කරුණාකර නැවත උත්සාහ කරන්න',
      'copied': 'පිටපත් කරන ලද!',
      'confirm_delete': 'ඔබ මෙම සටහන මකා දැමීමට විශ්වාසී ද?',
      'confirm_logout': 'ඔබ ඉවත් වීමට විශ්වාසී ද?',
      'ai_analyzing': 'AI ඔබේ සටහන විශ්ලේෂණ කරමින් පවතී...',
      'sentiment_positive': 'ධනාත්මක',
      'sentiment_negative': 'ඍණ',
      'sentiment_neutral': 'පරිසර',
      'export_pdf': 'PDF ලෙස අපනයන',
      'export_docx': 'DOCX ලෙස අපනයන',
      'export_txt': 'TXT ලෙස අපනයන',
      'archive': 'ගබඩාව',
      'unarchive': 'ගබඩා ඉවත් කරන්න',
      'pin': 'අල්පනා',
      'unpin': 'අල්පනා ඉවත් කරන්න',
    },
    'ta': {
      'app_title': 'Note Lingo',
      'welcome': 'Note Lingo இற்கு வரவேற்கிறோம்',
      'record': 'பதிவு செய்யவும்',
      'stop': 'நிறுத்தவும்',
      'save': 'சேமிக்கவும்',
      'cancel': 'ரத்துசெய்',
      'delete': 'நீக்கவும்',
      'edit': 'திருத்தவும்',
      'transcription': 'பெயர்ப்பு',
      'summary': 'சுருக்கம்',
      'category': 'வகை',
      'language': 'மொழி',
      'favorite': 'விருப்பமான',
      'unfavorite': 'விருப்பமற்ற',
      'share': 'பகிர்ந்து கொள்ளுங்கள்',
      'comments': 'கருத்துக்கள்',
      'analytics': 'பகுப்பாய்வு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறவும்',
      'loading': 'ஏற்றுவதில்...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'lecture': 'விரிவுரை',
      'meeting': 'கூட்டம்',
      'interview': 'நேர்காணல்',
      'personal': 'ব্যক্তিগত',
      'other': 'வேறு',
      'home': 'வீடு',
      'notes': 'குறிப்புகள்',
      'profile': 'சுயவிவரம்',
      'export': 'ஏற்றுமதி',
      'recent_notes': 'சமீபத்திய குறிப்புகள்',
      'no_notes': 'இன்னும் குறிப்புகள் இல்லை',
      'create_first_note': 'உங்கள் முதல் குறிப்பை உருவாக்கவும்',
      'tap_record': 'பதிவு செய்ய பதிவு பொத்தானைத் தொடவும்',
      'recording': 'பதிவு செய்தல்...',
      'processing': 'செயல்முறை...',
      'transcribing': 'பெயர்ப்பு...',
      'summarizing': 'சுருக்குமை...',
      'connecting_ai': 'AI சேவகனுக்கு இணைப்பு...',
      'ai_enhancements': 'AI மேம்பாடுகள்',
      'sentiment': 'உணர்வு',
      'speakers': 'பேச்சாளர்கள்',
      'keywords': 'முக்கிய சொற்கள்',
      'entities': 'நிறுவனங்கள்',
      'smart_folders': 'சமர்த்த கோப்புறைகள்',
      'add_comment': 'கருத்து சேர்க்கவும்...',
      'no_comments': 'இன்னும் கருத்துக்கள் இல்லை',
      'shared_with': 'என்னுடன் பகிர்ந்து கொள்ளப்பட்டது',
      'search': 'தேடல்',
      'filter': 'வடிப்பி',
      'sort': 'வரிசைப்படுத்து',
      'created': 'உருவாக்கப்பட்ட',
      'modified': 'மாற்றப்பட்ட',
      'duration': 'கால',
      'word_count': 'சொல் எண்ணிக்கை',
      'transcription_accuracy': 'பெயர்ப்பு துல்லியம்',
      'progress_stats': 'முன்னேற்ற புள்ளிவிவரங்கள்',
      'total_notes': 'மொத்த குறிப்புகள்',
      'total_minutes': 'மொத்த நிமிடங்கள்',
      'total_words': 'மொத்த சொற்கள்',
      'current_streak': 'தற்போதைய பட்டை',
      'by_category': 'வகைப்படுத்தப்பட்ட',
      'top_words': 'சிறந்த சொற்கள்',
      'favorites': 'விருப்பங்களை',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'retry': 'மீண்டும் முயற்சி செய்யவும்',
      'failed_to_save': 'குறிப்பு சேமிக்க தோல்வி',
      'please_try_again': 'மீண்டும் முயற்சி செய்யவும்',
      'copied': 'நகலெடுக்கப்பட்டது!',
      'confirm_delete': 'இந்த குறிப்பை நீக்க விரும்புகிறீர்களா?',
      'confirm_logout': 'வெளியேற விரும்புகிறீர்களா?',
      'ai_analyzing': 'AI உங்கள் குறிப்பை பகுப்பாய்வு செய்கிறது...',
      'sentiment_positive': 'நேர்மறை',
      'sentiment_negative': 'எதிர்மறை',
      'sentiment_neutral': 'நடுநிலை',
      'export_pdf': 'PDF ஆக ஏற்றுமதி செய்யவும்',
      'export_docx': 'DOCX ஆக ஏற்றுமதி செய்யவும்',
      'export_txt': 'TXT ஆக ஏற்றுமதி செய்யவும்',
      'archive': 'காப்பகம்',
      'unarchive': 'காப்பகத்தை அகற்றவும்',
      'pin': '핀',
      'unpin': 'அவ்வாறு அகற்றவும்',
    },
  };

  static String translate(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedStrings[locale]?[key] ??
        _localizedStrings['en']![key] ??
        key;
  }

  static String get(String locale, String key) {
    return _localizedStrings[locale]?[key] ??
        _localizedStrings['en']![key] ??
        key;
  }

  static List<String> get supportedLanguages => ['en', 'si', 'ta'];
}
