// Generates and shares note exports:
//  - PDF  (using the pdf package)
//  - TXT  (plain text)
//  - DOCX (RTF-based, opens in Word/Google Docs)

import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../models/note_model.dart';

class ExportService {
  // ── Singleton ────────────────────────────────────────────────
  static final ExportService _instance = ExportService._internal();
  factory ExportService() => _instance;
  ExportService._internal();

  // ════════════════════════════════════════════════════════════
  //  EXPORT ROUTER
  // ════════════════════════════════════════════════════════════

  Future<void> export(
    NoteModel note, {
    required String format,
    required bool includeSummary,
    required bool includeTranscript,
    required bool includeKeywords,
    required bool includeMeta,
  }) async {
    File file;

    switch (format) {
      case 'pdf':
        file = await exportToPdf(
          note,
          includeSummary: includeSummary,
          includeTranscript: includeTranscript,
          includeKeywords: includeKeywords,
          includeMeta: includeMeta,
        );
        break;
      case 'txt':
        file = await exportToTxt(
          note,
          includeSummary: includeSummary,
          includeTranscript: includeTranscript,
          includeKeywords: includeKeywords,
          includeMeta: includeMeta,
        );
        break;
      case 'docx':
        file = await exportToDocx(
          note,
          includeSummary: includeSummary,
          includeTranscript: includeTranscript,
          includeKeywords: includeKeywords,
          includeMeta: includeMeta,
        );
        break;
      default:
        throw Exception('Unknown export format: $format');
    }

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: note.title,
      text: 'Exported from Note Lingo',
    );
  }

  // ════════════════════════════════════════════════════════════
  //  PDF EXPORT
  // ════════════════════════════════════════════════════════════

  Future<File> exportToPdf(
    NoteModel note, {
    required bool includeSummary,
    required bool includeTranscript,
    required bool includeKeywords,
    required bool includeMeta,
  }) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('MMMM d, yyyy').format(note.createdAt);

    // Color palette
    const primaryColor = PdfColor.fromInt(0xFF6C63FF);
    const accentColor = PdfColor.fromInt(0xFF00D9B5);
    const lightBg = PdfColor.fromInt(0xFFF5F4FF);
    const textDark = PdfColor.fromInt(0xFF1A1A2E);
    const textMuted = PdfColor.fromInt(0xFF6B6882);
    const borderColor = PdfColor.fromInt(0xFFE5E4F0);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(44),
        // ── Header on every page ──────────────────────────────
        header: (ctx) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 10),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              bottom: pw.BorderSide(color: borderColor, width: 0.5),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Note Lingo',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: primaryColor,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                dateStr,
                style: pw.TextStyle(fontSize: 9, color: textMuted),
              ),
            ],
          ),
        ),
        // ── Footer on every page ──────────────────────────────
        footer: (ctx) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              top: pw.BorderSide(color: borderColor, width: 0.5),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Note Lingo AI',
                style: pw.TextStyle(fontSize: 8, color: textMuted),
              ),
              pw.Text(
                'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                style: pw.TextStyle(fontSize: 8, color: textMuted),
              ),
            ],
          ),
        ),
        build: (ctx) => [
          // ── Title block ──────────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              gradient: const pw.LinearGradient(
                colors: [
                  PdfColor.fromInt(0xFF6C63FF),
                  PdfColor.fromInt(0xFF9B59B6),
                ],
              ),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  note.title,
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Row(
                  children: [
                    _pdfPill(
                      '${note.category.emoji} ${note.category.label}',
                      PdfColors.white,
                    ),
                    pw.SizedBox(width: 8),
                    _pdfPill(
                      '${note.languageFlag} ${note.languageLabel}',
                      PdfColors.white,
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Metadata row ─────────────────────────────────────
          if (includeMeta) ...[
            pw.Container(
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: lightBg,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  _metaCell('📅 Date', dateStr),
                  _metaCell('⏱ Duration', note.formattedDuration),
                  _metaCell('📝 Words', '${note.wordCount}'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
          ],

          // ── Keywords ─────────────────────────────────────────
          if (includeKeywords && note.keywords.isNotEmpty) ...[
            _sectionHeader('Keywords', primaryColor),
            pw.SizedBox(height: 8),
            pw.Wrap(
              spacing: 6,
              runSpacing: 6,
              children: note.keywords
                  .map((k) => _pdfPill('#$k', primaryColor))
                  .toList(),
            ),
            pw.SizedBox(height: 20),
          ],

          // ── AI Summary ────────────────────────────────────────
          if (includeSummary && note.summary.isNotEmpty) ...[
            _sectionHeader('AI Summary', accentColor),
            pw.SizedBox(height: 8),
            pw.Container(
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: const PdfColor.fromInt(0xFFF0FDFB),
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(
                  color: const PdfColor.fromInt(0xFFB2F0E8),
                  width: 0.5,
                ),
              ),
              child: pw.Text(
                note.summary,
                style: pw.TextStyle(
                  fontSize: 11,
                  color: textDark,
                  lineSpacing: 5,
                ),
              ),
            ),
            pw.SizedBox(height: 20),
          ],

          // ── Full Transcript ───────────────────────────────────
          if (includeTranscript && note.transcription.isNotEmpty) ...[
            _sectionHeader('Full Transcript', primaryColor),
            pw.SizedBox(height: 8),
            pw.Container(
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: lightBg,
                borderRadius: pw.BorderRadius.circular(8),
                border: pw.Border.all(color: borderColor, width: 0.5),
              ),
              child: pw.Text(
                note.transcription,
                style: pw.TextStyle(
                  fontSize: 10.5,
                  color: textDark,
                  lineSpacing: 4,
                  height: 1.5,
                ),
              ),
            ),
          ],
        ],
      ),
    );

    // Save to temp directory
    final dir = await getTemporaryDirectory();
    final safeName = _safeName(note.title);
    final file = File('${dir.path}/$safeName.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  // ── PDF helpers ──────────────────────────────────────────────

  pw.Widget _sectionHeader(String title, PdfColor color) {
    return pw.Row(
      children: [
        pw.Container(
          width: 3,
          height: 18,
          decoration: pw.BoxDecoration(
            color: color,
            borderRadius: pw.BorderRadius.circular(2),
          ),
        ),
        pw.SizedBox(width: 8),
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
      ],
    );
  }

  pw.Widget _pdfPill(String text, PdfColor textColor) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: pw.BoxDecoration(
        color: textColor == PdfColors.white
            ? PdfColors.white.flatten(background: PdfColor.fromInt(0x33FFFFFF))
            : const PdfColor.fromInt(0xFFF0EEFF),
        borderRadius: pw.BorderRadius.circular(20),
      ),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          color: textColor,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  pw.Widget _metaCell(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 12,
            fontWeight: pw.FontWeight.bold,
            color: const PdfColor.fromInt(0xFF1A1A2E),
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 9,
            color: const PdfColor.fromInt(0xFF6B6882),
          ),
        ),
      ],
    );
  }

  // ════════════════════════════════════════════════════════════
  //  TXT EXPORT
  // ════════════════════════════════════════════════════════════

  Future<File> exportToTxt(
    NoteModel note, {
    required bool includeSummary,
    required bool includeTranscript,
    required bool includeKeywords,
    required bool includeMeta,
  }) async {
    final buf = StringBuffer();
    final dateStr = DateFormat('MMMM d, yyyy – HH:mm').format(note.createdAt);
    final sep = '─' * 52;

    buf.writeln('╔══════════════════════════════════════════════════╗');
    buf.writeln('  NOTE LINGO');
    buf.writeln('╚══════════════════════════════════════════════════╝');
    buf.writeln();
    buf.writeln(note.title.toUpperCase());
    buf.writeln(sep);

    if (includeMeta) {
      buf.writeln('Category : ${note.category.label}');
      buf.writeln('Language : ${note.languageLabel}');
      buf.writeln('Date     : $dateStr');
      buf.writeln('Duration : ${note.formattedDuration}');
      buf.writeln('Words    : ${note.wordCount}');
      buf.writeln(sep);
    }

    if (includeKeywords && note.keywords.isNotEmpty) {
      buf.writeln();
      buf.writeln('KEYWORDS');
      buf.writeln(note.keywords.map((k) => '#$k').join('  '));
      buf.writeln(sep);
    }

    if (includeSummary && note.summary.isNotEmpty) {
      buf.writeln();
      buf.writeln('AI SUMMARY');
      buf.writeln(note.summary);
      buf.writeln(sep);
    }

    if (includeTranscript && note.transcription.isNotEmpty) {
      buf.writeln();
      buf.writeln('FULL TRANSCRIPT');
      buf.writeln(note.transcription);
    }

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${_safeName(note.title)}.txt');
    await file.writeAsString(buf.toString(), flush: true);
    return file;
  }

  // ════════════════════════════════════════════════════════════
  //  DOCX EXPORT (RTF – opens in Word, Google Docs, Pages)
  // ════════════════════════════════════════════════════════════

  Future<File> exportToDocx(
    NoteModel note, {
    required bool includeSummary,
    required bool includeTranscript,
    required bool includeKeywords,
    required bool includeMeta,
  }) async {
    final dateStr = DateFormat('MMMM d, yyyy').format(note.createdAt);
    final buf = StringBuffer();

    // RTF header
    buf.write(r'{\rtf1\ansi\deff0');
    buf.write(
      r'{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fmodern\fcharset0 Courier New;}}',
    );
    buf.write(
      r'{\colortbl;\red108\green99\blue255;\red0\green217\blue181;\red26\green26\blue46;}',
    );
    buf.write(
      r'\paperw12240\paperh15840\margl1800\margr1800\margt1440\margb1440',
    );
    buf.write(r'\fs24\f0\cf3');
    buf.writeln();

    // Title
    buf.write(r'\cf1\fs36\b ');
    buf.write(_rtf(note.title));
    buf.write(r'\b0\fs24\cf3\par\par');

    // Meta
    if (includeMeta) {
      buf.write(r'\fs20\cf3 ');
      buf.write(
        'Category: ${_rtf(note.category.label)}   '
        'Language: ${_rtf(note.languageLabel)}   '
        'Date: ${_rtf(dateStr)}   '
        'Duration: ${_rtf(note.formattedDuration)}   '
        'Words: ${note.wordCount}',
      );
      buf.write(r'\par\par');
    }

    // Keywords
    if (includeKeywords && note.keywords.isNotEmpty) {
      buf.write(r'\cf1\fs22\b Keywords:\b0\cf3\fs20\par ');
      buf.write(note.keywords.map((k) => '#${_rtf(k)}').join('  '));
      buf.write(r'\par\par');
    }

    // Summary
    if (includeSummary && note.summary.isNotEmpty) {
      buf.write(r'\cf1\fs22\b AI Summary:\b0\cf3\fs20\par ');
      buf.write(_rtf(note.summary));
      buf.write(r'\par\par');
    }

    // Transcript
    if (includeTranscript && note.transcription.isNotEmpty) {
      buf.write(r'\cf1\fs22\b Full Transcript:\b0\cf3\fs20\par ');
      buf.write(_rtf(note.transcription));
      buf.write(r'\par');
    }

    buf.write('}');

    final dir = await getTemporaryDirectory();
    // Save as .rtf — Word and Google Docs open it natively
    final file = File('${dir.path}/${_safeName(note.title)}.rtf');
    await file.writeAsString(buf.toString(), flush: true);
    return file;
  }

  // ── RTF escaper ──────────────────────────────────────────────
  String _rtf(String text) {
    return text
        .replaceAll('\\', '\\\\')
        .replaceAll('{', '\\{')
        .replaceAll('}', '\\}')
        .replaceAll('\n', '\\par ');
  }

  // ── Safe filename ────────────────────────────────────────────
  String _safeName(String title) {
    return title
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .replaceAll(' ', '_')
        .substring(0, title.length.clamp(0, 40));
  }
}
